-- Public job boards verified reachable on 2026-09-30.
INSERT INTO companies (name, source, board_token) VALUES
    ('Affirm', 'GREENHOUSE', 'affirm'),
    ('Airbnb', 'GREENHOUSE', 'airbnb'),
    ('Airtable', 'GREENHOUSE', 'airtable'),
    ('Anthropic', 'GREENHOUSE', 'anthropic'),
    ('Asana', 'GREENHOUSE', 'asana'),
    ('Brex', 'GREENHOUSE', 'brex'),
    ('Carta', 'GREENHOUSE', 'carta'),
    ('Checkr', 'GREENHOUSE', 'checkr'),
    ('Chime', 'GREENHOUSE', 'chime'),
    ('Cloudflare', 'GREENHOUSE', 'cloudflare'),
    ('Coinbase', 'GREENHOUSE', 'coinbase'),
    ('Databricks', 'GREENHOUSE', 'databricks'),
    ('Datadog', 'GREENHOUSE', 'datadog'),
    ('Discord', 'GREENHOUSE', 'discord'),
    ('Dropbox', 'GREENHOUSE', 'dropbox'),
    ('Duolingo', 'GREENHOUSE', 'duolingo'),
    ('Elastic', 'GREENHOUSE', 'elastic'),
    ('Faire', 'GREENHOUSE', 'faire'),
    ('Figma', 'GREENHOUSE', 'figma'),
    ('Flexport', 'GREENHOUSE', 'flexport'),
    ('GitLab', 'GREENHOUSE', 'gitlab'),
    ('Gusto', 'GREENHOUSE', 'gusto'),
    ('Instacart', 'GREENHOUSE', 'instacart'),
    ('Lattice', 'GREENHOUSE', 'lattice'),
    ('Lyft', 'GREENHOUSE', 'lyft'),
    ('Mercury', 'GREENHOUSE', 'mercury'),
    ('MongoDB', 'GREENHOUSE', 'mongodb'),
    ('Nuro', 'GREENHOUSE', 'nuro'),
    ('Okta', 'GREENHOUSE', 'okta'),
    ('Pinterest', 'GREENHOUSE', 'pinterest'),
    ('Reddit', 'GREENHOUSE', 'reddit'),
    ('Robinhood', 'GREENHOUSE', 'robinhood'),
    ('Roblox', 'GREENHOUSE', 'roblox'),
    ('Samsara', 'GREENHOUSE', 'samsara'),
    ('Scale AI', 'GREENHOUSE', 'scaleai'),
    ('Squarespace', 'GREENHOUSE', 'squarespace'),
    ('Stripe', 'GREENHOUSE', 'stripe'),
    ('Toast', 'GREENHOUSE', 'toast'),
    ('Twilio', 'GREENHOUSE', 'twilio'),
    ('Vercel', 'GREENHOUSE', 'vercel'),
    ('Waymo', 'GREENHOUSE', 'waymo'),
    ('Webflow', 'GREENHOUSE', 'webflow'),
    ('Zscaler', 'GREENHOUSE', 'zscaler'),
    ('Aledade', 'LEVER', 'aledade'),
    ('Binance', 'LEVER', 'binance'),
    ('CI&T', 'LEVER', 'ciandt'),
    ('Crypto.com', 'LEVER', 'crypto'),
    ('Dun & Bradstreet', 'LEVER', 'dnb'),
    ('Hive', 'LEVER', 'hive'),
    ('JumpCloud', 'LEVER', 'jumpcloud'),
    ('Match Group', 'LEVER', 'matchgroup'),
    ('Outreach', 'LEVER', 'outreach'),
    ('Palantir', 'LEVER', 'palantir'),
    ('Ro', 'LEVER', 'ro'),
    ('Shield AI', 'LEVER', 'shieldai'),
    ('Spotify', 'LEVER', 'spotify'),
    ('Veeva', 'LEVER', 'veeva'),
    ('Zoox', 'LEVER', 'zoox');
